# Generated by Django 2.0.6 on 2018-07-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericuserfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genericuserfile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='genericuserfile',
            name='file',
            field=models.FileField(default=213, max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
