# Generated by Django 2.0.6 on 2018-07-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0002_auto_20180707_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1500)),
                ('screenshot',
                 models.FileField(max_length=200, upload_to='learningtopic/')),
            ],
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='topic',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='coderdojomobile.LearningTopic'),
        ),
    ]
