# Generated by Django 2.0.6 on 2018-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0003_auto_20180708_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='level',
            field=models.IntegerField(),
        ),
    ]
