# Generated by Django 2.0.6 on 2018-08-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0006_auto_20180721_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[(
                    'id',
                    models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                                    )
                    ),
                    ('value', models.DecimalField(
                                                 decimal_places=2,
                                                 max_digits=3
                                                 )),
                    ('rating_date', models.DateField()),
                    ('rating_source', models.CharField(max_length=45)),
                    ('rating_author', models.CharField(max_length=150)),
                    (
                    'material',
                    models.ForeignKey(
                                     on_delete=django.db.models.
                                     deletion.DO_NOTHING,
                                     to='coderdojomobile.LearningMaterial'
                                     )
                    ), ],
        ),
    ]
