# Generated by Django 2.0.6 on 2018-08-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0008_auto_20180804_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[(
                    'id',
                    models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                                    )
                    ),
                    ('title', models.CharField(max_length=200)),
                    ('description', models.CharField(max_length=1500)),
                    ('requisites', models.CharField(max_length=3000)),
                    (
                    'image',
                    models.OneToOneField(
                                        null=True,
                                        on_delete=django.db
                                        .models.deletion.CASCADE,
                                        related_name='+',
                                        to='coderdojomobile.GenericUserFile'
                                        )
                    ), ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='badges',
            field=models.ManyToManyField(
                                        null=True,
                                        related_name='_participant_badges_+',
                                        to='coderdojomobile.Badge'
                                        ),
        ),
    ]
