# Generated by Django 2.0.6 on 2018-08-18 19:02

from django.db import migrations


def create_os_names(apps, schema_editor):
    op_sys = apps.get_model('coderdojomobile', 'OperatingSystem')
    op_sys.objects.create(
                         title='Windows 10',
                         description='Windows 10 system')
    op_sys.objects.create(title='Windows 7', description='Windows 7 system')
    op_sys.objects.create(
                         title='Windows XP',
                         description='Windows XP system'
                         )
    op_sys.objects.create(title='Mac OS X', description='Mac OS X')
    op_sys.objects.create(title='Mac OS 10.5', description='Mac OS 10.5')


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0011_operatingsystem_softwaretool'),
    ]

    operations = [
        migrations.RunPython(create_os_names),
    ]
