# Generated by Django 2.0.6 on 2018-09-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojomobile', '0014_auto_20180830_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='_participant_badges_+', to='coderdojomobile.Badge'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='waiver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant', to='coderdojomobile.Waiver'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='scanned_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='waivers/'),
        ),
    ]
